// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Footer/Footer.tsx";
import * as $$$$$$1 from "./sections/Header/Header.tsx";
import * as $$$$$$2 from "./sections/Main/About.tsx";
import * as $$$$$$3 from "./sections/Main/CoreValues.tsx";
import * as $$$$$$4 from "./sections/Main/Main.tsx";
import * as $$$$$$5 from "./sections/Main/OurPortfolio.tsx";
import * as $$$$$$6 from "./sections/Main/OurTeam.tsx";
import * as $$$$$$7 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$8 from "./sections/Theme.tsx";
import * as $$$$$$$$$$$0 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/start/sections/Footer/Footer.tsx": $$$$$$0,
    "deco-sites/start/sections/Header/Header.tsx": $$$$$$1,
    "deco-sites/start/sections/Main/About.tsx": $$$$$$2,
    "deco-sites/start/sections/Main/CoreValues.tsx": $$$$$$3,
    "deco-sites/start/sections/Main/Main.tsx": $$$$$$4,
    "deco-sites/start/sections/Main/OurPortfolio.tsx": $$$$$$5,
    "deco-sites/start/sections/Main/OurTeam.tsx": $$$$$$6,
    "deco-sites/start/sections/Miscellaneous/CookieConsent.tsx": $$$$$$7,
    "deco-sites/start/sections/Theme.tsx": $$$$$$8,
  },
  "apps": {
    "deco-sites/start/apps/site.ts": $$$$$$$$$$$0,
  },
  "name": "deco-sites/start",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
